Neural Networks Test Script - 3 Layers

Stage 1: Import packages

In [1]:
import numpy as np

Stage 2: Sigmoid Function - creating proportions by turning values to values between 0 and 1

In [2]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

Stage 3: Input data

In [3]:
X = np.array([  [0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])

Stage 4: Output data

In [4]:
y = np.array([[0,1,1,0]]).T

Stage 5: Seeding Values - can manipulate the network to show any relationships

In [5]:
np.random.seed(1)

Stage 6: Creating Weights - syn0 creates weights for the hidden weights and syn1 creates the final weights

In [6]:
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]


In [7]:
print(syn0)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]


In [8]:
print(syn1)

[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


Stage 7: Loop

In [11]:
for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.4964100319027255
Error:0.008584525653247157
Error:0.00578945986250781
Error:0.004629176776769985
Error:0.00395876528027365
Error:0.0035101225678616753
